// User
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

// Location
export const ADD_CURRENT_LOCATION = "ADD_CURRENT_LOCATION";
export const ADD_LOCATION = "ADD_LOCATION";
export const CHANGE_NAME = "CHANGE_NAME";
export const START_RECORDING = "START_RECORDING";
export const STOP_RECORDING = "STOP_RECORDING";
export const RESET = "RESET";
export const DISCARD_RECORDING = "DISCARD_RECORDING";
export const CONFIRM_TRACK = "CONFIRM_TRACK";
export const SAVE_TRACK_SUCCESS = "SAVE_TRACK_SUCCESS";
export const SAVE_TRACK_FAIL = "SAVE_TRACK_FAIL";

// Tracks
export const FETCH_USER_TRACKS_REQUEST = "FETCH_USER_TRACKS_REQUEST";
export const FETCH_USER_TRACKS_SUCCESS = "FETCH_USER_TRACKS_SUCCESS";
export const FETCH_USER_TRACKS_FAIL = "FETCH_USER_TRACKS_FAIL";
export const FETCH_FEED_SUCCESS = "FETCH_FEED_SUCCES";
export const FETCH_FEED_FAIL = "FETCH_FEED_FAIL";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";
export const FETCH_TRACK_FAIL = "FETCH_TRACK_FAIL";
export const FETCH_MY_TRACKS_SUCCESS = "FETCH_MY_TRACKS_SUCCESS";
export const FETCH_MY_TRACKS_FAIL = "FETCH_MY_TRACKS_FAIL";
export const CLEAN_USER_TRACKS = "CLEAN_USER_TRACKS";
export const TRACK_LIKE_SUCCESS = "TRACK_LIKE_SUCCESS";
export const TRACK_LIKE_FAIL = "TRACK_LIKE_FAIL";

// Search
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FOLLOW_USER = "FOLLOW_USER";
export const CLEAR_USERS = "CLEAR_USERS";
